import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';

// Cleanup older caches
cleanupOutdatedCaches();

// Precache all assets generated by Vite build
precacheAndRoute(self.__WB_MANIFEST);

// Custom offline service worker logic
self.addEventListener('install', (event) => {
  self.skipWaiting();
});

self.addEventListener('activate', (event) => {
  event.waitUntil(self.clients.claim());
});
